### ISSUE TITLE
op.uri does not update, getmarketHistory does not accept count argument

### ISSUE THREAD

**Issue by svenwoldt** [n0mad01/node.bittrex.api#10]
Hey nomad,
I encountered two issues working with your api.

I try to set the count for the getMarketHistory method to anything but 20 but it does not accept the argument and always defaults to 20.
This method seems broken.
Further your op.uri does not update the iteratee in process and always hangs at BTC-ZRC market name as can be seen here at least for the console.log at the end of your pipe.
The iteration itself happens but op.uri does not change. Weird is that the console.log has the count argument correctly in it.
Last, the duration at the end does not seem to be seconds but milliseconds.

streamed from https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ZRC&count=50 in: 4.664s
streamed from https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ZRC&count=50 in: 4.677s
streamed from https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ZRC&count=50 in: 4.697s
streamed from https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ZRC&count=50 in: 4.708s

Your help would be much appreciated in fixing those issues.
Thank you very much for this library.

 Sven

**Comment by n0mad01** [comment]
I can't see a problem in node.bittrex.api, as you can see request URI is set correctly in both request and stream:

requested from https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ZRC&count=50 in: 0.252s
streamed from https://bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-ZRC&count=50 in: 0.261s

but i still count 20 objects that the Bittrex API returns:

``` javascript
bittrex.getmarkethistory( { market : 'BTC-ZRC', count : 50 }, function( data ) {
  console.log( data.result.length );
});
```

so, the problem seems to be on the side of Bittrex, they simply ignore the 'count' parameter and always return a set of 20 objects.

You could write an email to support@bittrex.com (from https://bittrex.com/Home/Contact) and simply ask/tell them about that issue (if they aren't aware of this already) and post their answer here.

**Comment by svenwoldt** [comment]
Hey thanks for your response.
Yes indeed it is a bittrex issue and I filled an issue on their support page.
I will let you know what comes out of it.

**Comment by svenwoldt** [comment]
The response from bittrex was that they updated the api and did not yet update the api doc section.
The getmarkethistory method no longer allows for a custom count argument.
Regards,
Sven

**Comment by n0mad01** [comment]
thanks,
i've updated the readme and i will close this issue as soon as Bittrex updates their API docs.

**Comment by svenwoldt** [comment]
Good to know nomad ;)

Can I ask you a question?
The issue arose for me trying to get request the tradehistory for all
market names on bittrex.
With those api changes I am currently only able to fetch the default 20
last trades for BTC-NXT ( for instance ) and de-duplicate those with 20
trades I already have saved in my db.
The whole iteration takes around 7 seconds. So if I update trades of quite
actively traded markets on a given moment I am not able to capture all the
trades that happened in between those 7 seconds for some market names.
My question is do you happen to know a strategy for collecting all the
trades that happen on bittrex that is effective?
Thanks in advance and for the exchange of information so far.
Kind regards,
Sven

**Comment by n0mad01** [comment]
hi,
first off, this doesn't belong in this thread and is rather a question for specific boards.

you could run every trading-pair in a separate instance, then every iteration should last only milliseconds, there aren't that many trades in the meanwhile, so you would'nt lose much data (as every trade has it's own numeric and iterative id) - but that would get too abusive on the API and you may get blocked for that.

if you need large datasets for historical analysis you could ask bittrex or look elsewhere:
https://www.cryptocoincharts.info/tools/api

in case you need fresh data for predictions you don't need absolutey all data, it's always possible that some trades 'get swallowed', but if you don't miss whole minutes and therefore tens or hundreds of trades then you're good to make predictions (although many pairs have less than 1 trade per hour!).
