### ISSUE TITLE
withdrawal

### ISSUE THREAD

**Issue by michel5** [n0mad01/node.bittrex.api#11]
how can i withdrawal with the api key?

**Comment by n0mad01** [comment]
a withrawal method is implemented:

``` javascript
bittrex.withdraw({ currency : 'BTC', quantity : '1.5112', address : 'THE_ADDRESS' }, function( data ) {
    console.log( data );
});
```

you may also use a custom request:

``` javascript
var url = 'https://bittrex.com/api/v1.1/account/withdraw?apikey=API_KEY&currency=EAC&quantity=20.40&address=EAC_ADDRESS';

bittrex.sendCustomRequest( uri, function( data ) {
    console.log( data );
});
```

you'll find more information on the specific API calls in the Bittrex documentation:
https://bittrex.com/Home/Api

**Comment by michel5** [comment]
how does that work with URL as your key example is ppppp and secret key ccccccc

**Comment by n0mad01** [comment]
Please consult the documentations as everything is described there.
