### ISSUE TITLE
[Error: socket hang up] code: 'ECONNRESET', sslError: undefined ?

### ISSUE THREAD

**Issue by hems** [n0mad01/node.bittrex.api#13]
From time to time i'm getting

```
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
```

Any idea of what might be happening?

On a side note, i believe the socket connection shouldn't have been made since i'm not using any socket related features ? ( i'm only checking order book )

this are the options i'm currently using:

```
    'apikey'    : process.env.BITTREX_KEY
    'apisecret' : process.env.BITTREX_SECRET
    'stream'    : false
    'verbose'   : false
    'cleartext' : false 
```

**Comment by n0mad01** [comment]
This will be most likely due to closed TCP connections, maybe the Bittrex API is overloaded, maybe you query the api too often (in this case try to throttle your API requests a little bit).

#socket connection - yes, you are using socket connections when you are doing http requests.

**Comment by hems** [comment]
@n0mad01 ha yeah sure, i meant using the push API i didn't think i would get a "socket hang up" error from doing http requests (( :
