### ISSUE TITLE
 'INVALID SIGNATURE'

### ISSUE THREAD

**Issue by michel5** [n0mad01/node.bittrex.api#15]
Hi

If i try request my balance from bittrex i have this error :
{ success: false, message: 'INVALID SIGNATURE', result: null }

How can i fix this??

**Comment by n0mad01** [comment]
hi,
can you please describe what caused the error and how you fixed it?

**Comment by michel5** [comment]
it was a api key problem

**Comment by n0mad01** [comment]
ok, i see.
good for you that you could fix that issue!
