### ISSUE TITLE
getorderbook ignores depth option

### ISSUE THREAD

**Issue by EricGrill** [n0mad01/node.bittrex.api#17]
Does not appear to get passed in the getorderbook method

**Comment by n0mad01** [comment]
yes, as it is ignoring the count argument in other cases/calls. please see also https://github.com/n0mad01/node.bittrex.api/issues/10

you are free to ask bittrex about this issue, they should have fixed it a long time ago https://bittrex.com/Home/Contact, it would be helpful if you could post their answer here.
