### ISSUE TITLE
Market Orders are disabled right now MARKET_ORDERS_DISABLED

### ISSUE THREAD

**Issue by stefek99** [n0mad01/node.bittrex.api#19]
To remove not supported method from the wrapper?

https://twitter.com/bittrexexchange/status/526590250487783425?lang=en

**Comment by n0mad01** [comment]
as long as they are covered in the official api docs there is no reason to remove them.

https://bittrex.com/home/api

**Comment by jinuem** [comment]
market Order is available or not? Not mentioned in Document

**Comment by n0mad01** [comment]
i have sent a ticket to the bittrex support to be clear on that and also to update the API docs - without answer so far.

but please note that in your API KEYS section (when logged in to bittrex https://bittrex.com/Manage#sectionApi) you have the following options: READ INFO, TRADE LIMIT, TRADE MARKET, WITHDRAW you can set for each used API Key, so standard is that TRADE MARKET is not allowed and you have to activate it first.

**Comment by jinuem** [comment]
@n0mad01  thank you

**Comment by ghost** [comment]
The actual function is not listed on their API doc anymore. Found this old [snapshot ](https://web.archive.org/web/20161108195951/https://bittrex.com/home/api) where it's still listed but it seems that they removed it. After some testing, I can confirm it's really disabled. Boo!

**Comment by n0mad01** [comment]
both calls got removed:
/market/buymarket
/market/sellmarket

**Comment by seeARMS** [comment]
Why was this issue closed? Market orders are still disabled but still present in the code.

**Comment by 001gouthi** [comment]
how can i place an sell_limit order which would be an immediate or cancel using the api ?

**Comment by jayarjo** [comment]
Same here: MARKET_ORDERS_DISABLED, even though apiKey has corresponding permissions.

**Comment by dektox** [comment]
Hi, try to place limit order instead with a higher price with option IMMEDIATE_OR_CANCEL

ticker = input('enter currency ticker ')
 current_rate = requests.get(url='https://bittrex.com/api/v1.1/public/getticker?market=btc-{}'.format(ticker))
    current_rate = current_rate.json()
    current_rate_result = current_rate['result']
    current_bid = current_rate_result['Bid']
    quasi_market_price = round(current_bid * 1.109, 8)
sell_market = my_bittrex.trade_sell('BTC-{}'.format(ticker), 'LIMIT', %quantity%, quasi_market_price, 'IMMEDIATE_OR_CANCEL', 'NONE', 0.0)

**Comment by cmosse** [comment]
Did anyone have success with this ImmediateOrCancel thing?

**Comment by mattiabugossi** [comment]
Out of curiosity why market orders got removed?
