### ISSUE TITLE
'marketsummaries' will not stream when bittrex.options : stream = true

### ISSUE THREAD

**Issue by TimLaMason** [n0mad01/node.bittrex.api#20]
When I use the following code to 'getmarketsummaries':
```
    var bittrex = require('/node.bittrex.api/node.bittrex.api.js');
    bittrex.options({
        'stream' : true,
	'verbose' : true,
	'cleartext' : false,
	'baseUrl' : 'https://bittrex.com/api/v1.1'
    });
    bittrex.getmarketsummaries(function(data) {
	for (var i in data.result) {
	    var mrkt = {
		symbol : data.result[i].MarketName,
		volume : data.result[i].Volume,
		last : data.result[i].Last,
		high : data.result[i].High,
		low : data.result[i].Low
		};
	console.log(mrkt);
	};
    });
```
I get the following response only:
```
    > streamed from https://bittrex.com/api/v1.1/public/getmarketsummaries in: 0.14s
    streamed from https://bittrex.com/api/v1.1/public/getmarketsummaries in: 0.156s
    streamed from https://bittrex.com/api/v1.1/public/getmarketsummaries in: 1.063s
```

If I change option stream to false, I get an array of objects with correct results. (far too many to show).
If I am approaching this wrong, please let me know.
Thanks,

**Comment by n0mad01** [comment]
please don't use the stream option anymore, it will be removed in further versions - it was a mistake from the beginning the way it was implemented.
` 'stream' : false`

use simple api calls or the new implemented websocket methods instead!
https://github.com/n0mad01/node.bittrex.api#websockets
