### ISSUE TITLE
Websocket API

### ISSUE THREAD

**Issue by dparlevliet** [n0mad01/node.bittrex.api#21]
Hey,

I needed access to the Bittrex real-time API for market changes/tickers, etc - I couldn't find any nodejs library that supported it and their API documentation doesn't even mention it, but it does exist. Anyway, I needed to figure out how to get access and I thought you could use my findings. 

The code isn't implementable as-is but it shouldn't take much more work for you to integrate it. Hope you can make use of it - if not, that's OK too.

```bash
npm install --save signalr-client jsonic
```

```nodejs
var jsonic = require('jsonic');
var signalR = require('signalr-client');


var client = new signalR.client(
  "wss://socket.bittrex.com/signalr",
  ['CoreHub']
);


/**
 * Example data:
 * {
    "MarketName": "BTC-ANS",
    "High": 0.001525,
    "Low": 0.00075611,
    "Volume": 2296953.44814714,
    "Last": 0.0014202,
    "BaseVolume": 2638.26486332,
    "TimeStamp": "2017-06-17T12:04:08.53",
    "Bid": 0.0014361,
    "Ask": 0.0014369,
    "OpenBuyOrders": 1022,
    "OpenSellOrders": 514,
    "PrevDay": 0.000769,
    "Created": "2016-10-26T01:28:31.96"
  }
 */
function tickerUpdate(pairCode, data) {
  console.log('Ticker Update for '+pairCode, data);
};


/**
 * Example data:
 *  {
      "MarketName": "BTC-ETH",
      "Nounce": 661678,
      "Buys": [
        {
          "Type": 1,
          "Rate": 0.0886264,
          "Quantity": 0
        },
        {
          "Type": 1,
          "Rate": 0.08743581,
          "Quantity": 0
        },
        {
          "Type": 1,
          "Rate": 0.08616772,
          "Quantity": 0
        },
        {
          "Type": 1,
          "Rate": 0.08577644,
          "Quantity": 0
        },
        {
          "Type": 1,
          "Rate": 0.08576411,
          "Quantity": 0
        }
      ],
      "Sells": [
        {
          "Type": 0,
          "Rate": 0.13989973,
          "Quantity": 40
        },
        {
          "Type": 2,
          "Rate": 0.1399704,
          "Quantity": 0.10334389
        }
      ],
      "Fills": []
      }
    }
 */
function marketUpdate(pairCode, data) {
  console.log('Market Update for '+pairCode, data);
}


function subscribeToMarkets() {
  [ 'BTC-ETH', 'BTC-SC' ].forEach(function(market) {
    client.call('CoreHub', 'SubscribeToExchangeDeltas', market).done(function(err, result) {
      if (result === true) {
        console.log('Subscribed to ' + market);
      }
    });
  });
};

client.serviceHandlers = {
  bound: function() { 
    console.log("Websocket bound"); 
  },
  connectFailed: function(error) { 
    console.log("Websocket connectFailed: ", error); 
  },
  connected: function(connection) {
    subscribeToMarkets();
    console.log("Websocket connected"); 
  },
  disconnected: function() { 
    console.log("Websocket disconnected"); 
  },
  onerror: function (error) { 
    console.log("Websocket onerror: ", error); 
  },
  messageReceived: function (message) {
    try {
      var data = jsonic(message.utf8Data);
      /**
       * updateSummaryState example:
       * {
          "C": "...",
          "M": [
            {
              "H": "CoreHub",
              "M": "updateSummaryState",
              "A": [
                {
                  "Nounce": 254683,
                  "Deltas": [
                    {
                      "MarketName": "BTC-ANS",
                      "High": 0.001525,
                      "Low": 0.00075611,
                      "Volume": 2296953.44814714,
                      "Last": 0.0014202,
                      "BaseVolume": 2638.26486332,
                      "TimeStamp": "2017-06-17T12:04:08.53",
                      "Bid": 0.0014361,
                      "Ask": 0.0014369,
                      "OpenBuyOrders": 1022,
                      "OpenSellOrders": 514,
                      "PrevDay": 0.000769,
                      "Created": "2016-10-26T01:28:31.96"
                    }, .. ]
                }
              ]
            }
          ]
       }
       * updateExchangeState example:
       * {
          "C": "...",
          "M": [
            {
              "H": "CoreHub",
              "M": "updateExchangeState",
              "A": [
                {
                  "MarketName": "BTC-ETH",
                  "Nounce": 661678,
                  "Buys": [
                    {
                      "Type": 1,
                      "Rate": 0.0886264,
                      "Quantity": 0
                    },
                    {
                      "Type": 1,
                      "Rate": 0.08743581,
                      "Quantity": 0
                    },
                    {
                      "Type": 1,
                      "Rate": 0.08616772,
                      "Quantity": 0
                    },
                    {
                      "Type": 1,
                      "Rate": 0.08577644,
                      "Quantity": 0
                    },
                    {
                      "Type": 1,
                      "Rate": 0.08576411,
                      "Quantity": 0
                    }
                  ],
                  "Sells": [
                    {
                      "Type": 0,
                      "Rate": 0.13989973,
                      "Quantity": 40
                    },
                    {
                      "Type": 2,
                      "Rate": 0.1399704,
                      "Quantity": 0.10334389
                    }
                  ],
                  "Fills": []
                }
              ]
            }
          ]
        }
       */
      if (data && data.M) {
        data.M.forEach(function(M) {
          switch (M.M) {
            case 'updateSummaryState':
              M.A.forEach(function(data) {
                data.Deltas.forEach(function(marketsDelta) {
                  tickerUpdate(marketsDelta.MarketName, marketsDelta);
                });
              });
              break;
            case 'updateExchangeState':
              M.A.forEach(function(data) {
                marketUpdate(data.MarketName, data);
              });
              break;
          }
        })
      } else {
        console.log('Unhandled data', data);
      }
    } catch (e) {
      console.error(e);
    }
    return false; 
  },
  bindingError: function (error) { 
    console.log("Websocket bindingError: ", error); 
  },
  connectionLost: function (error) { 
    console.log("Connection Lost: ", error); 
  },
  reconnecting: function (retry) {
    console.log("Websocket Retrying: ", retry);
    // change to false to stop retrying
    return true;
  }
};

```

**Comment by n0mad01** [comment]
great stuff, thanks a lot!
i implemented this right away: https://github.com/n0mad01/node.bittrex.api#websockets

(and also mentioned you as a contributor https://github.com/n0mad01/node.bittrex.api#contributors)

**Comment by dparlevliet** [comment]
nice! no probs

**Comment by ertygiq** [comment]
@dparlevliet Hi, how did you know that Websocket connection is possible with Bittrex? They don't mention it in their docs https://bittrex.com/home/api .

**Comment by dparlevliet** [comment]
I didn't see it mentioned but I knew they had to update the order books somehow and only an insane team (Liqui.io) wouldn't use websockets for that.

**Comment by dparlevliet** [comment]
If you're asking specifically how I found it then all I did was open the Developer tools in Chrome and look at the ``WS`` tab in the ``Network`` section. The harder part was figuring out what type of sockets they were using, but thankfully there were some clues in the connection string.

**Comment by ertygiq** [comment]
Oh, I got it. Thank you.
I thought that they may have hidden docs or info was leaked)

**Comment by ertygiq** [comment]
I'm thinking of doing such kind of investigation for another exchange. Is there a way to see actual data sent through websocket connection in Developer tools? On WS tab I just see different connections. 'Some connections' -> Frames is empty.

**Comment by dparlevliet** [comment]
That's definitely the right area - but I can't tell you exactly if what you're seeing is right or wrong.

**Comment by ertygiq** [comment]
![2017-08-26 16_06_31- 0 00013770 btc-byc bytecent](https://user-images.githubusercontent.com/17641403/29741584-b4032712-8a78-11e7-97b9-9c9fcd4fc617.png)

I'm seeing this.

**Comment by dparlevliet** [comment]
Uhm, I think the content box is overlapping the frames box because your resolution is so small. You should be able to grab and drag the black line that's going under the "Enter regex... " - pull it down and you should see the frames.

**Comment by n0mad01** [comment]
@alexvelickiy please, could you take this questions to a more specific board?
there is plenty material out there to learn how to inspect websocket traffic.
use the issues here only for specific questions, thanks.

**Comment by ertygiq** [comment]
@n0mad01 sorry, sure I could.

**Comment by sagivo** [comment]
would be nice to add documentation to the WebSocket options (including orders like buy/sell)

**Comment by Amindv1** [comment]
What does the output from subscribe represent?

"Type": 1,
"Rate": 0.0886264,
"Quantity": 0
Buys
Sells
Fills
Nonce

what are fills vs buys vs sells? how can the quantity be 0 ? what is Type?

**Comment by rotemx** [comment]
@Amindv1 I guess that 0 means that the order is deleted.

I thought that type 0 = sell and type 1 = buy, but WTF is type=2 !?

**Comment by kattatzu** [comment]
Rather, I believe that zero means adding and one eliminates (if you realize the records with zero in the amount comes zero as well), since the categories already say "buy / sell", I think it works just like Binance where they are grouped amounts by price.

Example:

{Type: 0, Rate: 0.07247907, Quantity: 0.01061322}

The item "0.07247907" with 0.01061322 of stock is added.

Y

{Type: 1, Rate: 0.07251045, Quantity: 0},

The item "0.07251045" is deleted since the quantity is zero.

regards

**Comment by kattatzu** [comment]
On the contrary, I think zero means adding and one eliminates (if you realize that records with zero in the amount are also zero), since the categories already say "buy / sell", I think it works just like Binance, where amounts are grouped by price

Example:

{Type: 0, Rate: 0.07247907, Quantity: 0.01061322}

The item "0.07247907" is added with 0.01061322 of the shares.

Y

{Type: 1, Rate: 0.07251045, Quantity: 0},

The article "0.07251045" is deleted since the quantity is zero.

regards

**Comment by kattatzu** [comment]
Query, does anyone know if Bittrex has a Snapshot to preload the database before connecting to the Websocket?
