### ISSUE TITLE
cancelling subscribe

### ISSUE THREAD

**Issue by ddaddy** [n0mad01/node.bittrex.api#22]
Hi,
Is there a way to cancel a subscribe websocket?

**Comment by n0mad01** [comment]
in short: i don't know (yet)
there are currently no official docs on the websockets API, so i don't know the correponding call (if there is such a call at all). 
let's pretend there would be such a call and it would be named UNKNOWN_UNSUBCRIBE_CALL, then the code would go like this:

```javascript
var websocketsclient = bittrex.websockets.subscribe(['BTC-ETH'], function(data) {});

websocketsclient.call('CoreHub', 'UNKNOWN_UNSUBCRIBE_CALL', ['BTC-ETH']).done(function(err, result) {});
```

**Comment by ddaddy** [comment]
I have emailed Bittrex support. I'll let you know if I get a response.
