### ISSUE TITLE
websocket API - question

### ISSUE THREAD

**Issue by alexandrei892** [n0mad01/node.bittrex.api#23]
I am using the websockets.subscribe example to get live market data for a specific pair.

Can someone tell me or point me in the right direction regarding the **Type** values for the _Buys_ and _Sells_ ?

I can see they take values in the 0..2 range, I would like to know what each value means.
I noticed that many, if not all, of the Type = 1 have Quantity = 0. What does this mean?

Thanks!
Alex

**Comment by ilyacherevkov** [comment]
If you are talking about subscribeToExchangeDeltas, my guess is that

EDITED:
0 – new order entries at matching price, you need to add it to the orderbook
1 –  cancelled / filled order entries at matching price, you need to delete it from the orderbook
2 – changed order entries at matching price (partial fills, cancellations), you need to edit it in the orderbook

**Comment by ilyacherevkov** [comment]
Additional methods discovered:

Authenticated (i don't know how to pass authentication):
SubscribeToUserDeltas() – returns nothing
QueryBalanceState() – returns null
QueryOrderState(market) –returns null

Public:
QueryExchangeState(market) – snapshot of orderbook
QuerySummaryState() – all markets stats
SubscribeToExchangeDeltas(market) – orderbook deltas feed

**Comment by alexandrei892** [comment]
This is the example i'm using

```
bittrex.websockets.subscribe(['BTC-NMR'], function(data) {
  if (data.M === 'updateExchangeState') {
    data.A.forEach(function(data_for) {
        console.log(data_for);
    });
  }
});
```

As you suggest, Type = 1 being a partially filled order, why would the Quantity be reported as 0?
Also, I think the executed orders, are stored in the _Fills_ array, containing the direction BUY or SELL and the rest of the details.

Do I assume correctly that _Buys_ and _Sells_ are order book entries and _Fills_ are executions?

Example:

```
{ MarketName: 'BTC-NMR',
  Nounce: 184483,
  Buys:
   [ { Type: 0, Rate: 0.02876107, Quantity: 17.68076595 },
     { Type: 1, Rate: 0.02876101, Quantity: 0 },
     { Type: 2, Rate: 0.02876012, Quantity: 52.13647914 },
     { Type: 2, Rate: 0.02860004, Quantity: 4.19028224 },
     { Type: 1, Rate: 0.0286, Quantity: 0 },
     { Type: 0, Rate: 0.02816669, Quantity: 12.2195475 },
     { Type: 1, Rate: 0.02816668, Quantity: 0 },
     { Type: 0, Rate: 0.02816667, Quantity: 0.01775148 },
     { Type: 1, Rate: 0.02800007, Quantity: 0 } ],
  Sells:
   [ { Type: 2, Rate: 0.0290191, Quantity: 1.87490152 },
     { Type: 2, Rate: 0.02986273, Quantity: 4.51738611 },
     { Type: 1, Rate: 0.03112025, Quantity: 0 },
     { Type: 0, Rate: 0.03144945, Quantity: 6.18211661 },
     { Type: 0, Rate: 0.03447746, Quantity: 0.12494129 },
     { Type: 0, Rate: 0.03901847, Quantity: 0.02 } ],
  Fills:
   [ { OrderType: 'BUY',
       Rate: 0.0290191,
       Quantity: 0.06609416,
       TimeStamp: '2017-06-26T14:39:29.087' } ] }
```

**Comment by ilyacherevkov** [comment]
I've confused type 1 and 2:

Type 0 – you need to add this entry into your orderbook. There were no orders at matching price before.

Type 1 – you need to delete this entry from your orderbook. This entry no longer exists (no orders at matching price)

Type 2 – you need to edit this entry. There are different number of orders at this price. 

Buys, Sells are bids / asks, and Fills are trades.

**Comment by ilyacherevkov** [comment]
You can also call QueryExchangeState(market) to get full snapshot of orderbook

**Comment by ilyacherevkov** [comment]
Guys from bittrex made this guide
[WebSocketAPI_MarketTracking.docx](https://github.com/n0mad01/node.bittrex.api/files/1104308/WebSocketAPI_MarketTracking.docx)

Authenticated methods are in the works!

**Comment by alexandrei892** [comment]
Hi Ilya,
thanks for your help so far, I didn't manage to call the new methods. can I trouble you for some examples or some guidance with the implementation?

Thanks again!
Alex

**Comment by tdurbin86** [comment]
Ilya,

In your example you are checking for (data.M === 'updateExchangeState').  However, I also receive websocket data where (data.M === 'updateSummaryState').  Can you please advise on what 'updateSummaryState' means?  Do I need to process these to keep my order book accurate?

Thanks,
Tom

**Comment by waikchiu5** [comment]
I watched the bittrex document and still cant understand the "type" value. Like @ilyacherevkov said. It maybe related the operation of order book.

**Comment by dparlevliet** [comment]
Yes, it tells you what has happened in the order book.

**Comment by p0ntsNL** [comment]
so how is it possible to keep the lowest ask price available at the orderbook?

Can this be done by always using type 2?

Also, updateSummaryState data (for example ask and bid) are not instant, I can see some delay on them compared to updateExchangeState... is that normal?

**Comment by gmanroney** [comment]
hi,

I'm trying to get 
- tradeid
- price
- quantity
- timestamp
- side (buy/sell)

I THINK the dataset you are describing above is what i need but i'm still on the learning curve as far as the business side of this is concerned.

is this the right data source? i don't think trade id is available but the others might with some arithmetics 

my interpretation is that i can get the timestamp from the fills sometimes but not all the time which is clearly not good. is this right?

my code on this can be found at https://github.com/gmanroney/cryptoboard

cheers

g

**Comment by MoroZvlg** [comment]
Should I skip 'Fills' if i want manage order book only?
