### ISSUE TITLE
Websocket question

### ISSUE THREAD

**Issue by bugduino** [n0mad01/node.bittrex.api#24]
Hi,
I would like to know if there is a way with the new websocket api to be notified when one of my orders  has been filled. Is there something else besides 'updateSummaryState'?

I found this snippet in your examples folder 

```
websocketsclient.serviceHandlers.messageReceived = function (message) {
  console.log(message);
}
```

could this be used in some way? Should I use one of the `listen` or `subscribe` events?
Thank you

**Comment by rastapasta** [comment]
Will need authentication to work first - see https://github.com/n0mad01/node.bittrex.api/issues/23#issuecomment-311262113

**Comment by bugduino** [comment]
Ah ok, Is It a bittrex problem or a node.bittrex.api problem?

Il mer 28 giu 2017, 15:04 Michael Straßburger <notifications@github.com> ha
scritto:

**Comment by LRonHubs** [comment]
Where can i find documentation for the bittrex websocket api? I would like to use it to get a live orderbook snapshot. I could contribute the code if it's an easy push / someone knows where this is already
