### ISSUE TITLE
SignalR Websocket subscribe from React App framework: TypeError: WebSocketClient not a constructor.

### ISSUE THREAD

**Issue by junkomatic** [n0mad01/node.bittrex.api#30]
With the objective of simply testing the websocket subscription for orderbook updates within the ReactJS framework, here are the steps I have taken:

-Used create-react-app to create the app.
-used npm to install the node.bittrex.api module
-added the 'bittrex' client object to the top of the default App.js component and configured options with proper API keys, as in docs
-added a button (with handler, binded to the button according to React docs) to the default App.js main component,
-inside the handler function, initiated the websocket subscription according to the example code in the node.bittrex.api docs.
-npm start

The app loads, but when I press the button, I get an error saying that TypeError Websocketclient() is not a constructor, in the line inside the SignalR.js that creates the websocket connection. Is this because React is using a different websocket module than is expected? What to do?

**Comment by junkomatic** [comment]
`import React, { Component } from 'react';`
`import logo from './logo.svg';`
`import './App.css';`

`var bittrex = require('../node_modules/node.bittrex.api/node.bittrex.api.js');`
`bittrex.options({`
`          'apikey' : process.env.REACT_APP_BTREX_API_KEY,`
`      'apisecret' : process.env.REACT_APP_BTREX_SECRET_KEY, `
`      'verbose' : true,`
`      'cleartext' : false, `
`      'baseUrl' : 'https://bittrex.com/api/v1.1'`
`    });`

`class App extends Component {`

`  constructor(props) {`
`    super(props);`
`    this.handleClick = this.handleClick.bind(this);`
`  }`

`  handleClick() {`
`    bittrex.websockets.subscribe(['BTC-ETH','BTC-ANS','BTC-GNT'], function(data) {`
`      if (data.M === 'updateExchangeState') {`
`        data.A.forEach(function(data_for) {`
`          console.log('Market Update for '+ data_for.MarketName, data_for);`
`        });`
`      }`
`    });`


`  }`

`  render() {`
`    return (`
`      <div className="App">`
`        <div className="App-header">`
`          <img src={logo} className="App-logo" alt="logo" />`
`          <h2>Welcome to React</h2>`
`        </div>`
`        <br/>`
`        <button onClick={this.handleClick}>Start WS Sub</button>`
`      </div>`
`    );`
`  }`
`}`

`export default App;`

**Comment by n0mad01** [comment]
this is similar to #28 
like i said there, webbrowser support is planned but i can't give a precise date at the moment.
