### ISSUE TITLE
"depth" parameter for getorderbook method has no effect

### ISSUE THREAD

**Issue by ldcicconi** [n0mad01/node.bittrex.api#35]
When calling the getorderbook method like in the example : 
`bittrex.getorderbook({ market : 'BTC-LTC', depth : 10, type : 'both' }, function( data, err ) {console.log( data );});`
, the depth parameter does not have an effect on the returned value. Whether depth is 1, 10, or 99, `getorderbook()` returns what seems to be the entire orderbook (~1400 orders for LTC).

**Comment by ldcicconi** [comment]
Upon further investigation, it seems the [Bittrex API](https://bittrex.com/home/api) does not accept this parameter . Perhaps this is deprecated.

**Comment by n0mad01** [comment]
yes, this parameter hasn't been working for quite a while now but only recently they finally removed it from the API docs.
