### ISSUE TITLE
callback error, data order is inversed

### ISSUE THREAD

**Issue by hems** [n0mad01/node.bittrex.api#36]
Hello i just noticed that you have ( data, error ) as arguments for your callback functions when node.js "standard" is the opposite, it uses error first. as in: ( error, data ).

By using the standard your functions will be ready to plug 'n play in loads of node.js libraries, like Promises, async and many other "callback hell workarounds" !

Thanks for sharing the repo, i'll be doing more tests during the next several weeks.

**Comment by n0mad01** [comment]
i know, the problem is that in the beginning i had only 1 parameter (the data param where also errors were returned), @dparlevliet added the error object but as second param because otherwise it would break backward compatibility.

i could add the objects sequence as an option - i'll think about that.

**Comment by dparlevliet** [comment]
Yes, if we can always make a setting which would flip the params passed - this would allow people who have already built things to continue to receive upgrades without breaking the apps while allowing new people who are more familiar with the NodeJS convention to use it.

**Comment by dparlevliet** [comment]
@hems and @n0mad01 if you agree that a setting would suffice I can implement it quite easily. I think for a project like this one breaking changes should be avoided if possible.

**Comment by n0mad01** [comment]
thanks @dparlevliet but i've already released a version with the option 'inverse_callback_arguments' which does exactly that.

**Comment by hems** [comment]
cool!

thanks guys!

maybe there should be a new "major release" which has the callbacks inverted by default and no option ( like all the other node.js packages would do! ) but that is definitely good enough!

Thank you
