### ISSUE TITLE
getorderhistory returns only orders from last 30 days

### ISSUE THREAD

**Issue by saschb2b** [n0mad01/node.bittrex.api#37]
I just noticed that. I am using this data for calculation but with only a 30 day timeframe it's useless.
Is it bittrex' fault? Or do you have an idea on how to recive all orders?

```
new Promise((resolve, reject) => bittrex.getorderhistory({market: 'BTC-LTC'},data => {
      if (data instanceof Object)
        resolve(data)
    }))
```
returns LTC orderHistory but only from the last 30 days.

The docs also don't say that.

```
new Promise((resolve, reject) => bittrex.getorderhistory({},data => {
      if (data instanceof Object)
        resolve(data)
    }))
```
returns all orderHistory for ALL currencies but it's capped to 500 entries...

**Comment by dparlevliet** [comment]
This library does not impose any rules on any calls so this would be a Bittrex issue - or at least a limitation in the current API. I know the Bittrex website is currently using a new API, but they haven't yet released any documentation for it. My order history on the website currently only provides the last 200 orders, so you shouldn't rely on it providing 500 in the future. 

The website does have a URL call (via the "Load All" button) to download your entire history ``https://bittrex.com/api/v2.0/auth/orders/DownloadFullOrderHistory`` but it does not work via the current API methods.

Personally I keep track of my own history in a local database, you might have to look at doing the same if you need a longer history. You can start by manually downloading your entire history as a CSV. 

If the new API gets documentation we will be able to provide further advice on whether it's possible to get a longer history, but currently there isn't a way.

**Comment by saschb2b** [comment]
Ok sent a ticket for further information to bittrex. Didn't saw the csv download button yesterday. Seems I have to keep track of the order manually. Thanks

**Comment by n0mad01** [comment]
@saschb2b ok then, i'll close this ticket but could you write a followup with the answer you got from bittrex when/if you get a response?

@dparlevliet thanks for picking up!

**Comment by saschb2b** [comment]
So far no answer from my ticket. But found this old record. With a count parameter. Doesn't work anymore https://web.archive.org/web/20140716170136/https://bittrex.com/Home/Api

**Edit**:
Bittrex uses v2.0 internally. For order history they call
`https://bittrex.com/Api/v2.0/auth/market/GetOrderHistory`

The parameters are:
* `MarketName` like `BTC-DASH`
* `__RequestVerificationToken` which is just a long token string

The response is like 
```
{
"success":true,
"message":"",
"result":[{
the usual results here
}]
}
```

**Edit 2:**
It's a POST request now instead of GET. Why does bittrex use a POST request for **GET**orderHistory?

But I can't get it to work editing your build.
That's everything I could find out so far. Will report back if I got something new.

**Edit 3:**
Here is some java dude showing of a java beta version for apiv2 https://github.com/platelminto/java-bittrex-2/blob/master/src/Bittrex.java

**Comment by saschb2b** [comment]
Got an answer finally

> Hi,
> 
> Unfortunately that function has been deprecated.  We plan to release a new version of our API in the next several months with improvements to the order depth.  In the meantime, if you want tick data, you may want to investigate using tradingview which now supports all Bittrex markets.
> Thank you,
> 
> Travis @ Bittrex
> 
> Follow us on Twitter @ https://twitter.com/BittrexExchange

**Comment by Ornolfr** [comment]
@saschb2b Do you know what the `__RequestVerificationToken` is and how can it be obtained?

**Comment by 6** [comment]
@Ornolfr: `__RequestVerificationToken` refers to two different values. One is the session cookie value, which remains valid for a session. The other refers to the CSRF token, which changes every time you refresh the page. (not sure why bittrex named these both the same)

Here's how to get what you need to make the V2 GetOrderHistory request:

1. Login to bittrex.com and use Chrome DevTools (or equivalent) to get cookie values for `__RequestVerificationToken` + `.AspNet.ApplicationCookie`. See below screenshot for example:

<img width="571" alt="screen shot 2017-10-21 at 8 51 01 pm" src="https://user-images.githubusercontent.com/158675/31857094-8d59a428-b6a2-11e7-9891-57fd1f6378a2.png">

2. View HTML source of logged in bittrex.com and grab the value of the CSRF token from `<input name="__RequestVerificationToken" type="hidden" value="COPY_THIS_VALUE">`.

Finally, make the below request

```
POST https://bittrex.com/api/v2.0/auth/market/GetOrderHistory
Content-Type: application/x-www-form-urlencoded
Cookies: __RequestVerificationToken=REPLACE_WITH_SESSION_COOKIE; .AspNet.ApplicationCookie=REPLACE_ME

marketname=BTC-LTC&__RequestVerificationToken=REPLACE_WITH_CSRF_TOKEN
```

Note that these values may expire frequently, and you'll have to get new values.

**Comment by lcryp-founder** [comment]
Can I get more than 50 trades by the team "https://bittrex.com/api/v2.0/key/market/getorderhistory?marketname=BTC-LTC" ?
