### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by treidio** [n0mad01/node.bittrex.api#41]
account.bittrex.buylimit( {market:currencyPair, quantity: account.staking/values.wa5min , rate : values.wa5min * 1.02}, (res, err) => {
                if (err) {
                        console.log(err);
                } else if (res) {
                       console.log(res);

occasionally yields

/home/ubuntu/node_modules/node.bittrex.api/node.bittrex.api.js:131
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:                 callback(null, result));
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:                 ^
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]: TypeError: callback is not a function
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at Request._callback (/home/ubuntu/node_modules/node.bittrex.api/node.bittrex.api.js:131:17)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at Request.self.callback (/home/ubuntu/node_modules/request/request.js:188:22)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at emitTwo (events.js:87:13)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at Request.emit (events.js:172:7)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at Request.<anonymous> (/home/ubuntu/node_modules/request/request.js:1171:10)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at emitOne (events.js:77:13)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at Request.emit (events.js:169:7)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at IncomingMessage.<anonymous> (/home/ubuntu/node_modules/request/request.js:1091:12)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at IncomingMessage.g (events.js:260:16)
Aug 13 09:56:47 ip-172-31-40-182 bot_USDT-NEO[972]:     at emitNone (events.js:72:20)

this results in my code not acknowledging a buy order

best regards :)

**Comment by n0mad01** [comment]
this looks as if the arrow callback function is somehow not handed over correctly or the function itself is not properly assembled before it's handed over.

can you check which type the function is (typeof) before the call and also what type you get back (in case of the incorrect ones)?

**Comment by treidio** [comment]
I think I found it.

        if (account.sellOrderNo != 0){
                account.bittrex.cancel({uuid : account.sellOrderNo});
                account.sellOrderNo = 0;
        };

/home/ubuntu/node_modules/node.bittrex.api/node.bittrex.api.js:131
 callback(null, result));
 ^
TypeError: callback is not a function

but there is no callback. so thats true..

**Comment by n0mad01** [comment]
could you solve that for you? 
can you share your solution (and some insights why this happened in the first place)?

**Comment by treidio** [comment]
I just added an empty function to the call..

**Comment by n0mad01** [comment]
ok, thanks
