### ISSUE TITLE
error first callback

### ISSUE THREAD

**Issue by oktapodia** [n0mad01/node.bittrex.api#47]
Hello,

First, thanks for your library!

I saw something which breaks promisify and the `bluebird.fromCallback`

A lot of libraries follow the [error first callback](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/)

I want to make a pull request about that, but I want first to know if it's something mergeable for you or not

Thanks by advance for your answer

**Comment by dparlevliet** [comment]
Yes, this is supported but not as standard for backward compatability reasons. Please see ``inverse_callback_arguments`` in https://github.com/n0mad01/node.bittrex.api#configure

**Comment by oktapodia** [comment]
Ok thanks for answer!
