### ISSUE TITLE
Api key invalid after add my key

### ISSUE THREAD

**Issue by lionel95200x** [n0mad01/node.bittrex.api#56]
Hello

After parameters my data and update my keys on admin panel

bittrex.options({
    'apikey': '93XXXX012XXXXXXXXXXXXXca1bXXXXXa',
    'apisecret': 'a2XXXXXXXXXXXXXXXXX5e4908262',
    'cleartext': true,
    'baseUrl': 'https://bittrex.com/api/v1.1',
});

When i make a simple call like getBalances
 bittrex.getbalance({
        currency: 'BTC'
    }, function(data, err) {
        if (err) {
            return console.error(err);
        }
        console.log(data);
    });

I got an error { success: false, message: 'APIKEY_INVALID', result: null }

Can you help me ? i have forgot something ?

Thanks

**Comment by n0mad01** [comment]
please check your api key's permissions for READ INFO on the bittrex website.

**Comment by bernatfortet** [comment]
@lionel95200x did you selve this issue? I'm having the same problem
