### ISSUE TITLE
Meaning of H and "Nounce" parameters?

### ISSUE THREAD

**Issue by moxious** [n0mad01/node.bittrex.api#63]
In data coming back via web sockets, we see things like this:

```
{"H":"CoreHub","M":"updateExchangeState","A":[{"MarketName":"USDT-ZEC","Nounce":73530,"Buys":[{"Type":0,"Rate":249.56100001,"Quantity":4.10941386}],"Sells":[{"Type":0,"Rate":253.944,"Quantity":14.903},{"Type":1,"Rate":253.945,"Quantity":0},{"Type":0,"Rate":253.94597411,"Quantity":6.366}],"Fills":[]}]}
```

What here does "H" stand for, and what other values are there besides CoreHub?   Additionally, what does the Nounce value signify?

**Comment by dparlevliet** [comment]
The H signifies the Hub/Channel the message came from. CoreHub is the only hub available so the value will always be that.

Nounce is an id that can only be used once https://en.wikipedia.org/wiki/Cryptographic_nonce
