### ISSUE TITLE
APIKEY_INVALID

### ISSUE THREAD

**Issue by bernatfortet** [n0mad01/node.bittrex.api#64]
I've tried everything possible:
1. node.bittrex.api
2. normal request pinging a url
3. Postman
4. creating a new account
5. Creating new keys

but I always end up getting this message:
`results {"success":false,"message":"APIKEY_INVALID","result":null}`

What am I doing wrong?

**Comment by bernatfortet** [comment]
It turned out that I had an extra space in my apikey.
I found out by looking at the url that was being sent out.

**Comment by hems** [comment]
This happens from time to time even with valid api keys. i believe this is an issue on Trex side and i have already called a ticket on them. hoping they sort this soon, it's surely breaking loads of apps.
